import { SessionProvider } from 'next-auth/react';
import './styles.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <SessionProvider>
        <body>{children}</body>
      </SessionProvider>
    </html>
  )
}
